"""Exercise 1.14: 

Draw the tree illustrating the process generated by [the count-change 
procedure of section 1.2.2](https://mitpress.mit.edu/sites/default/files/sicp/full-text/book/book-Z-H-11.html#%_sec_1.2.2) 
in making change for 11 cents. 

What are the orders of growth of the space and number of steps used by 
this process as the amount to be changed increases?
"""

# I will skip drawing the tree for now

"""

"""
